# Server配置
server:
  port: 8080
  # servliet配置
  servlet:
    context-path: /zcatp

# 应用名称
spring:
  application:
    name: zcatp

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcatp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    #自动提交
    default-auto-commit: true
    #指定updates是否自动提交
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

  # 配置jpa
  jpa:
    # 配置 DBMS 类型
    database: mysql
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    hibernate:
      # 配置开启自动更新表结构
      ddl-auto: update


## mybatis 配置
#mybatis:
#  #指定Mybatis的Mapper文件
#  mapper-locations: classpath:mappers/*xml
#  #指定Mybatis的实体目录
#  type-aliases-package: com.fjzcit.zcatp.mybatis.entity

